CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    authority VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS note (
      id IDENTITY PRIMARY KEY,
      title VARCHAR(100) NOT NULL CHECK (LENGTH(title) >= 2 AND LENGTH(title) <= 100),
      content VARCHAR(1000) NOT NULL CHECK (LENGTH(content) <= 1000),
      user_id BIGINT NOT NULL,
      CONSTRAINT fk_note_user FOREIGN KEY (user_id) REFERENCES "user"(id)
);